language: objective-c

xcode_project: DFCache.xcodeproj

before_script:
    - brew update
    - brew upgrade xctool

matrix:
  include:
    - xcode_scheme: 'DFCache iOS'
      xcode_sdk: iphonesimulator
    - xcode_scheme: 'DFCache OS X Static'
